aurelia/binding

src/ast.js
Evaluate equality operator before null check. Currently, comparison with null doesn't work as expected and always evaluates to null.
For example, the following element will never be shown:
```html
<div if.bind="someValue == null">...</div>
```
=> fix(ast): correct (in)equality operators against null operands

README.md, config.js, package.json, src/observer-locator.js, test/adapter.js, test/observer-locator.spec.js
Enabling plugins to supply property observation adapters allows breeze to efficiently observe properties in situations where it would otherwise resort to dirty checking
Fixes #9
=> feat(observer-locator) enable plugins to supply property observation adapters

src/array-change-records.js
addedCount was set to 1 on delete which caused an empty viewSlot to be added after removal
=> fix(array-change-records): set addedCount to 0 on delete

src/index.js, src/map-change-records.js, src/map-observation.js, src/observer-locator.js
Basically I copied the array observe structure. Change records use key instead of index, and we don't have to deal with splices, which simplifies stuff.
=> feat(map-observation): implement map observation

src/observer-locator.js, src/property-observation.js, test/observer-locator.spec.js
Added UndefinedPropertyObserver, to be used when the property does not exist.
Fixes #23
=> fix(observer-locator) ObserverLocator assumes OoPropertyObserver when property is undefined

src/listener-expression.js
Before, all events were `defaultPrevented` by default. Now, if the result of a callback is exactly true, `event.preventDefault()` is NOT called.
closes #16
=> fix(listener-expression): use result of event handler for preventDefault behavior

src/array-change-records.js, src/array-observation.js, src/collection-observation.js, src/map-observation.js
I took a shot extracting base classes (collection-observation) for array-observation and map-observation. They contained a lot of duplicated code. Let me know if you see any issues or improvements. It's pretty scary to touch this before we get the unit tests in place.
My earlier fix (https://github.com/aurelia/binding/commit/fb6cbe9fd2574994787e2da43a5526f655ab21d2) for addedCount only fixed when delete. Update should still have addedCount 1. Fix for this should be included as well.
=> collection-observation base class

src/computed-observation.js, src/index.js, src/observer-locator.js, test/computed-observation.spec.js
=> feat(ObserverLocator) observe computed properties via their dependencies

src/property-observation.js, test/binding-expression.spec.js
Removed the `HTMLSelectElement.selectedItems` polyfill because it caused problems with Safari and only Internet Explorer needed it.  All tests passing and the integration tests work in Chrome, Firefox and IE.  Wasn't able to test Safari because of another issue is preventing the app from loading.  Here's the safari error at startup:
``` bash
[Error] SyntaxError: Cannot declare a parameter named 'fetch' as it shadows the name of a strict mode function.
appendChild (skeleton-navigation, line 88)
doEval (system.js, line 1)
__eval (system.js, line 1)
a (system.js, line 1)
instantiate (system.js, line 1)
instantiate (system.js, line 1)
instantiate (system.js, line 1)
instantiate (system.js, line 1)
instantiate (system.js, line 1)
instantiate (system.js, line 1)
(anonymous function) …
```
=> fix(SelectValueObserver) Safari and Internet Explorer

src/event-manager.js
IE doesn't fire change/input events on contenteditable elements.
=> fix(EventManager): Internet Explorer contenteditable

src/binding-expression.js, src/binding-modes.js, test/access-keyed-observer.spec.js, test/checked-observer.spec.js, test/select-value-observer.spec.js
BREAKING CHANGE: This is a breaking API change that moves the ONE_WAY, TWO_WAY, and ONE_TIME constants into a bindingMode object with oneWay, twoWay, and oneTime properties.
=> refactor(binding-modes): move binding mode constants into bindingModes object

src/ast.js
fixes aurelia/templating-binding#37
=> fix(AST): do not coerce operands of || or && to booleans

src/map-observation.js, src/property-observation.js, src/value-converter.js
We were previously using `import core from core-js` which generates d.ts that do not match the corejs d.ts. This is now updated to `import * as core 'core-js'`, which resolves TypeScript compilation warnings.
closes https://github.com/aurelia/framework/issues/177
=> fix(binding): Use correct import for core-js

package.json, src/binding-expression.js, src/element-observation.js, test/access-keyed-observer.spec.js, test/element-observation.spec.js
Previously when passed a null or undefined value, a
ValueAttributeObserver would set the value of that html element to
a string representation of that value. This patch changes that
behavior to be more in line with the initial BindingExpression
behavior of setting that value to an empty string.
=> fix(ValueAttributeObserver): set undefined/null to empty string

src/map-observation.js
This checks the `oldValue` against `undefined` to have type `update` if the oldValue was set but falsy.
=> check old value against undefined on map set

src/observer-locator.js, test/adapter.js, test/observer-locator.spec.js, test/shared.js
This change also streamlines the ObjectObservationAdapter API, resulting in an easier to implement and more performant interface.
Fixes jdanyow/aurelia-computed#8
=> fix(ObserverLocator): enable adapter installation after instantiation

src/binding-system.js, test/binding-system.spec.js
@EisenbergEffect this is a work in progress.  Let me know what you think.
The current design would require us to add the following somewhere in aurelia framework:
```js
import {initializeBindingSystem} from 'aurelia-binding';
initializeBindingSystem(container);
```
To use this outside of an Aurelia application, `initializeBindingSystem()` would be required although we could refactor the BindingSystem class to make the static methods lazy initialize when they're called to support the external or unit-test scenarios more cleanly.
My thinking was this would preserve our ability to have one instance of services like the TaskQueue and EventManager in the container while still enabling external and unit-testing scenarios.
Remaining work:
* remove DI dependency in package.json
* fixup templating …
=> feat(BindingSystem): add binding system API

src/array-observation.js
Handle out of bounds splices same way as native implementation
Fixes aurelia/templating-resources#103
=> fix(array-observation): handle out of bounds splices

src/element-observation.js, test/checked-observer.spec.js, test/select-value-observer.spec.js
This change enables developers to specify a matcher function (equality comparer) when binding to select value attributes or checkbox/radio checked attributes. If a matcher function is not supplied the default matcher (===) will be used.
Fixes #94
=> feat(select): enable matcher functions

src/subscriber-collection.js, test/subscriber-collection.spec.js
Fixes #252, Fixes jdanyow/aurelia-computed#12
Handles scenarios where observers have subscriptions that overflow into the 'rest' buckets and calling one observer's subscribers causes another observer's subscribers to be called
=> fix(subscriberCollection): handle cascading calls

src/element-observation.js, test/element-observation.spec.js
Regex was splitting style strings at all : and breaking urls
Fixes #301
=> fix(StyleObserver): parse style without breaking urls

src/array-observation.js, src/map-observation.js, src/observer-locator.js, src/set-observation.js, test/array-observation.spec.js, test/map-observation.spec.js, test/set-observation.spec.js
I have noted that for Array instance Observer created in two distinct private properties. Even more, those instances where not the same depending on which API you use to create and retrieve them. This PR fixes management of observers for Collection types by ensuring that for one given instance of collection always will be only one MutationObserver instance.
=> fix (observer-locator): observer locator for collections must return same instance of Observer for same instance collection

src/map-observation.js, src/set-observation.js, test/map-observation.spec.js, test/set-observation.spec.js
As far as I understood it is not possible to extend Maps & Sets using the Babel transpiler (at least for now). That's  too bad, as I would like to create a class similar to this:
```
export NumericSet extends Set {
constructor() {
}
add(val) {
if (typeof val === 'number') {
super.add(val);
}
}
}
```
As expected, when I transpile this using Babel I get the following error:
```
TypeError: Method Set.prototype.add called on incompatible receiver #<NumericSet>
```
I tried to overcome this issue by overwriting the `add` method of my Set instance directly. Unfortunately, this does not work either, as Aurelia overwrites my `add` method using the native `Set.prototype.add`.
This PR could help me out be calling the `add` method directly rather than using the prototype by default. I've changed the …
=> fix(*-observation): allow binding extended Map/Set

.travis.yml
This adds a simple TravisCI configuration to ensure that the project is always linted. If/when travis is enabled for this project, all commits/PRs will run travis jobs to catch early errors before code makes it into the main repo. Travis can also run karma tests via `xvfb` if we want to go down this road. 
/cc @bryanrsmith (I spoke with Rob and Jeremy about this, I believe you were working on CI at one point?)
=> chore(travis): add travis configuration

src/checked-observer.js, src/observer-locator.js, test/checked-observer.spec.js, test/observer-locator.spec.js
When checkbox/radio's value attribute is data-bound, observe it for changes and synchronize the element's checked status accordingly
fixes #320
=> fix(CheckedObserver): synchronize on changes to input value

config.js, package.json, src/array-observation.js, src/decorator-observable.js, src/map-observation.js, src/observer-locator.js, src/property-observation.js, src/set-observation.js, test/observer-locator.spec.js
First of all, this PR is not complete.
For some types of objects I wish not to allow adding properties after initialization (using `Object.preventExtensions()`). However, this also prevents Aurelia from observing these properties, as defining the required extra properties using `Object.defineProperty` fails. Currently, this is being ignored silently. This purpose of this PR is to add logging to the situations where this might occur.
I've you find this PR useful, I can add loggers for the other `Object.defineProperty` occurrences as well.
By the way, I actually find `Reflect.defineProperty` to be a more elegant solution than try & catching. But as this requires an extra polyfill in aurelia-polyfills, I hereby first mention it as a suggestion.
=> Log warning when property can't be defined

src/property-observation.js, test/observer-locator.spec.js
When creating a property like this:
```
Reflect.defineProperty(obj, 'foo', {
configurable: true,
enumerable: false, // <-- non-enumerable
set: setter,
get: getter
});
```
the property observer will add its own setter and getter (which is a good thing), but also sets the `enumerable` setting to `true`.
This PR makes the observer respect the existing setting.
=> Respect non-enumerable properties

doc/example/binding-binding-behaviors/custom/app.html
The output tag is more semantic for what we're trying to achieve here and it will allow me to write more general and reusable css.
=> Suggest changing logging <div> to <output> tag

doc/article/en-US/binding-radios.md
3x Motherboard as Content, Should be Motherboard, CPU, Memory
=> typo in examples

src/aurelia-binding.d.ts
The null and undefined types are a feature of TypeScript 2.0, which hasn't been released yet.
See #487.
=> (aurelia-binding.d.ts): remove TypeScript 2.0 syntax

src/element-observation.js, test/element-observation.spec.js
Fix for https://github.com/aurelia/templating-resources/issues/248
Should parse anything with function(s), strings or plain values:
_example patterns_
```
abc-xyz: value;  abc: "value"; abc: 'value';
abc: func("..."); abc: func('...'); abc: func(...);
abc: func(test), func("test") func('...') "s:t\"ri;ng: ";
abc: e-f(g(...), xyz); 
background: url(data:image/gif;base64,X//YZ...);
```
=> fix(StyleObserver): parse complex styles

src/decorator-observable.js, test/decorator-observable.spec.js
I ran into an issue where I could not determine which property was causing the handler function to be called when using the same function for watching multiple different properties. This PR adds the name of the property as the third argument of the change handler function, which resolves my issue.
=> Add property key to change handler arguments

src/element-observation.js, test/element-observation.spec.js
Inline styles must use `!important` to overwrite `!important` stylesheet rules.
fixes aurelia/templating-resources/issues/251
=> fix(StyleObserver): enable !important override

src/decorator-observable.js, test/decorator-observable.spec.js
Makes the decorator chainable by letting the system install the property and return the descriptor.
This doesn't change the observable implementation strategy (enumerable field, non-enumerable accessor, etc.)
=> Partial fix for #501

src/decorator-observable.js, test/decorator-observable.spec.js
Related: https://github.com/aurelia/binding/issues/511.
=> fix(observable): fix descriptor having both value and get and set

src/element-observation.js
The previous if statement check would break things if the value was undefined, as such, indexOf which was being checked for would not exist on an undefined/null value. The better check to do is just ensure that value exists as this seems to be a better way of handling this numeric edge case.
=> fix(styleobserver): improper value check in if

src/element-observation.js, test/element-observation.spec.js
The property methods (`set|removeProperty`) don't recognize _camelCased_ names.
fixes #523
=> fix(StyleObserver): convert camelCase properties to kebab-case

doc/article/en-US/binding-basics.md
<input type="text" value.bind="taskName" line has a missing bracket, messing with code highlighting in docs.
=> Added missing bracket for input element

src/ast.js, src/unparser.js
Add a global free variable `FEATURE_NO_UNPARSER` that can be used to remove `Unparser` from the build.
`Unparser` is mainly a debugging feature that is not used by consumers of Aurelia. The only visible change when removing it is that calling `toString()` on an `Expression` returns `[object Object]` instead printing the AST back to a string.
Removing `Unparser` cuts approx. 2K of minified code.
**Caution**: `Unparser` is presently used by `aurelia-validation` and can't be removed from an application that uses it. See aurelia/validation#412.
=> refactor(size): Unparser opt-out

src/ast.js
I am working on a project using i18n and ValidationController. In my translations file I wanted to be able to make a variable lowercase by using a ValueConverter:
"ERRORMESSAGES": {
"required": "${$displayName} is required",
"matches": "${$value} is not a valid ${$displayName| toLowercase }"
}
Using this I got the following error:
Unhandled rejection TypeError: Cannot read property 'valueConverters' of undefined
I inspected the code in vendor-bundle.js and found the problem was in ast.js of aurelia-binding. After changing the code it worked well. Now, where possible, the parameter lookupFunctions is passed to the chained evaluate method.
=> Fix for Unhandled rejection TypeError: Cannot read property 'valueConverters' of undefined

src/parser.js, test/parser.spec.js
Fixes https://github.com/aurelia/framework/issues/791
I haven't implemented a unit test for this as I cannot get the unit tests working.
=> fix(ParserImplementation): allow use of  $parent with | or & expressions

src/binding-expression.js, src/binding-mode.js, test/binding-expression.spec.js
This PR addresses:  
* *Add one-way-out binding* aurelia/templating-binding#33
Related:
* aurelia/templating-binding#114
```js
bindingMode.fromView
bindingMode.toView // alias of bindingMode.oneWay
```
Usage: 
```html
<input value.from-view='message' />
<my-input input.from-view='message' />
```
Note:
* It feel a bit Yoda when reading the view code
* [Demo](https://gist.run/?id=7c1ff795122a6e0b9bfe31ba88be6d85)
Edit:
* cc @EisenbergEffect @jdanyow @Vheissu
=> feat(Binding): fromView, toView

src/event-manager.js, src/listener-expression.js, test/event-manager.spec.js
This PR is aimed to address change in `Listener` proposed in #604 , to use the instance as listener in `bind` instead of creating a new arrow function.
In my local, test 'connects 100 bindings immediately before queueing rest' in `connect-queue.spec.js` breaks as it only flushes around 90 - 91 in queueMicroTask. I'm not sure why.
=> refactor(EventManager): Support handle event

src/checked-observer.js, src/element-observation.js, src/event-manager.js, src/select-value-observer.js
This PR replaced
* `checked-observer.js`, `select-observer.js`: `this.synchronizeValue.bind(this, false)` with `handleEvent() -> this.synchronizeValue()`
* `ValueAttributeObserver`: this.notify.bind(this, false)` with `handleEvent() -> this.notify()`
I'm don't see bound parameter `false` used anywhere in `synchronizeValue` functions so I think it's safe to remove. Tests remain the same.
=> refactor(Element Observation): use handleEvent instead of bind

src/ast.js, src/signals.js, test/binding-expression.spec.js
This PR:
* Addresses #353 Value converters should support triggering updates
* Has potential integration with `BindingSignaler` in `templating-resources`, where signaling in there will also trigger here, treating signal universal
* Still needs tests (WIP)
* Usage:
```js
export class LocaleValueConverter {
signals: string | string[] = 'locale-changed'
}
// usage
import { ConverterSignaler } from 'aurelia-binding';
ConverterSignaler.signal('some-thing');
```
* [Demo](https://gist.run/?id=e99a86c05beea939b9c900bf533f59d4)
* [Updated Demo](https://gist.run/?id=2f3f613fc5a1ca100e9f881e9feb0dce)
@jdanyow @EisenbergEffect @thomas-darling @davismj
=> feat(ValueConverter): enable signal

dist/aurelia-binding.d.ts
PR #655 only accounted for the splice returned when observing an array. This fix includes Map and Set observer splices. Adds typings for #607.
=> fix(typescript) ICollectionObserverSplice support for Map and Set

doc/article/en-US/binding-class-and-style.md
explaines https://github.com/aurelia/templating-binding/issues/100
=> fix(doc): css-attribute without interpolation explained

dist/aurelia-binding.d.ts, src/aurelia-binding.d.ts, src/event-manager.js, src/listener-expression.js, test/event-manager.spec.js
This PR enable `dispose()` on `EventManager.addEventListener`, which will help reduce memory usage for aurelia app, regardless `delegate`, `capture` or `trigger` commands used, as it will not return an anonymous function, but a disposable object instead. Breaking change: no, only return `Disposable` when the fifth parameter is truthy, can be made `true` only to have stricter API.
@jdanyow @EisenbergEffect
=> perf(EventManager): enable dispose() pattern for addEventListener

dist/aurelia-binding.d.ts, src/aurelia-binding.d.ts, src/event-manager.js
The `dispose()` should not be called more than once, but we can't control what binding behavior does, so put this check `element === null` in to avoid error
=> fix(EventSubscriber): do nothing if disposed

src/select-value-observer.js, test/select-value-observer.spec.js
fixes #521
fixes #614
fixes aurelia/framework#717
fixes aurelia/templating-binding#124
----
recheck https://github.com/aurelia/i18n/issues/147
The existing mutation observer config works in situations where the number of `<option/>` elements changes, but fails where only the text content of those element change. Probably because of this, we didn't get a many reports from folks who use hierarchical select bindings.
all fixes demo at https://fix-select.bigopon.surge.sh/
@jdanyow @EisenbergEffect
=> fix(SelectValueObserver): observe characterData mutation

src/ast.js, src/expression-cloner.js, src/parser.js, src/unparser.js, test/parser.spec.js
Chain isn't used anywhere and also can't be parsed from any valid expression. It appears to be a completely redundant expression.
Look only at the last commit
@bigopon
=> refactor(ast/parser): remove Chain

src/parser.js, test/parser.spec.js
fixes #700 
@EisenbergEffect this fixes a subtle regression and makes member expression parsing more compliant with https://tc39.github.io/ecma262/#prod-MemberExpression
=> fix(parser): allow PrimaryExpression on the lefthand side of CallMember

package.json, src/array-observation.js
Things may still go horribly wrong if one ended up having two versions of `aurelia-binding` in the final bundle, but at least array patching won't happen twice. Also trim some unnecessary fat out
Edit: this will work as long as there is no difference between v1 and v2 `ModifyArrayObserver` / `ModifyCollectionObserver`
@EisenbergEffect Should we also replace global `karma start` with npm script ?
resolves #699
=> fix(ArrayObservation): ensure patch applied only once

src/array-observation.js
@EisenbergEffect 
resolves #706
=> fix(array-observation): make marker non enumerable

src/aurelia-binding.d.ts
Correction to the ICollectionObserverSplice interface. Adding missing methods to the InternalCollectionObserver interface and ObserverLocator class.
One thing I noticed with the InternalCollectionObserver interface was the `subscribe(callback: (changeRecords: any) => void): void;` and `unsubscribe(callback: (changeRecords: any) => void): void;` method definitions; am I crazy to think that these are not supported / depreciated?
=> Update Collection Observer Typings

.npmignore
Apparently I am having some modules that require a different version of some aurelia modules and these reports folders are over 1MB each. There might be even more to gain in this area.
EDIT: Let me know which directories/files can also be added to this list and I will update this PR. Noticed also other Aurelia repo's can have this directory. Let me know if you need me to submit a PR there too.
=> Reduce node_modules directory size

build/tasks/build.js
In my previous attempt at #740, `declaration` in `tsconfig` was changed to false to make build not override type definition file in dist. But proper fix is to run `build-dts` task after all other tasks, so it would always make sure we have right type definitions in distribution
@EisenbergEffect @fkleuver
=> fix(build): run build-dts after all others

src/aurelia-binding.d.ts
Make property optional to prevent infinite loop in typing.
Closes #756
=> fix(typing): Make parentOverrideContext optional

src/event-manager.js
Return correct original event target for Firefox
Closes #765
=> fix(event-manager): Firefox shadow dom event handling
